import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import {useState} from 'react'
import {BsSearch} from 'react-icons/bs'



export default function Home() {

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

const url = `https://api.openweathermap.org/data/2.5/forecast?q=dubai&appid={process.env.NEXT_PUBLIC-WEATHER_KEY}`

const fetchWeather = (e) => {
  e.preventDefault()
  setLoading(true)
  axios.get(url).then((response) => {
    setWeather(response.data)
    console.log(response.data)
  });
  setCity('')
  setLoading(false);
}

  return (
    <div>
  
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div className="absolute top-0 left-0"/>
     
      <Image 
       src="https://images.unsplash.com/photo-1564296592999-a1614681006b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjEyfHx3ZWF0aGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60"
       layout='fill'
      //  className='object-cover'
      />

    </div>
    
  );
}